### ISSUE TITLE
Unhandled rejection ServerError: Upload failed to complete (HTTP 500/InternalSer verError)

### ISSUE THREAD

**Issue by jiereal** [tinify/tinify-nodejs#1]

**Comment by jiereal** [comment]
```
    at Error.ConnectionError (C:\websites\PICS\node_modules\tinify\lib\tinify\Er
ror.js:37:9)
    at ClientRequest.<anonymous> (C:\websites\PICS\node_modules\tinify\lib\tinif
y\Client.js:83:14)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
Unhandled rejection ConnectionError: Error while connecting: read ECONNRESET
    at Error.ConnectionError (C:\websites\PICS\node_modules\tinify\lib\tinify\Er
ror.js:37:9)
    at ClientRequest.<anonymous> (C:\websites\PICS\node_modules\tinify\lib\tinif
y\Client.js:83:14)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
Unhandled rejection ConnectionError: Error while connecting: read ECONNRESET
    at Error.ConnectionError (C:\websites\PICS\node_modules\tinify\lib\tinify\Er
ror.js:37:9)
    at ClientRequest.<anonymous> (C:\websites\PICS\node_modules\tinify\lib\tinif
```

This output may help you.

**Comment by warflower** [comment]
Thanks for the feedback.

A `read ECONNRESET` error means that the connection that you make to our API is abruptly closed.
Did you get this error once, or do you get it often while using our API?

**Comment by rolftimmermans** [comment]
Closing this now. Please let us know if you can provide more details. A `ConnectionError` usually means there is an issue with the network connection.
